### ISSUE TITLE
Import useEffect in TeacherList

### ISSUE THREAD

**Issue by karinasantosfelippe** [danileao/nlw2#1]
_nlw2/web/src/pages/TeacherList/index.tsx_

O que esse bloco de código faz? Ou foi postado acidentalmente? 

```
useEffect(() => {
    AsyncStorage.getItem("favorites").then((response) => {
      if (response) {
        setFavorites(JSON.parse(response));
      }
    });
  }, []);
```

Não precisaria exportar o useEffect no react?
E ter a função setFavorites?

**Comment by danileao** [comment]
@karinasantosfelippe Obrigada :) Commitei acidentalmente na pressa :) 
É pra uso somente no mobile, mas como estava com os 3 projetos no mesmo vscode, acabei colocando na classe errada, mas já alterei e commitei :)

**Comment by danileao** [comment]
> _nlw2/web/src/pages/TeacherList/index.tsx_
> 
> O que esse bloco de código faz? Ou foi postado acidentalmente?
> 
> ```
> useEffect(() => {
>     AsyncStorage.getItem("favorites").then((response) => {
>       if (response) {
>         setFavorites(JSON.parse(response));
>       }
>     });
>   }, []);
> ```
> 
> Não precisaria exportar o useEffect no react?
> E ter a função setFavorites?

**Comment by karinasantosfelippe** [comment]
Eu imaginei que fosse isso mesmo, rs. Também estou com os três abertos aqui.
Mas na dúvida, preferi perguntar :)

**Comment by danileao** [comment]
> Eu imaginei que fosse isso mesmo, rs. Também estou com os três abertos aqui.
> Mas na dúvida, preferi perguntar :)

É  a pressa pra poder ajudar vocês :)
